apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deploymentName }}
  labels:
    app: {{ .Values.deploymentName }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.deploymentName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
