apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: simple-app-template
  annotations:
    description: "Template pour déployer une application simple avec des paramètres personnalisables."

# change me : APP_NAME, APP_IMAGE, ENVIRONMENT
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    name: ${APP_NAME}
    labels:
      app: ${APP_NAME}
  spec:
    replicas: 1
    selector:
      app: ${APP_NAME}
    template:
      metadata:
        labels:
          app: ${APP_NAME}
      spec:
        containers:
        - name: ${APP_NAME}
          image: ${APP_IMAGE}
          ports:
          - containerPort: 8080
            protocol: TCP
          env:
          - name: ENVIRONMENT
            value: ${ENVIRONMENT}
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APP_NAME}
  spec:
    selector:
      app: ${APP_NAME}
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: ${APP_NAME}
  spec:
    to:
      kind: Service
      name: ${APP_NAME}
    port:
      targetPort: 8080